name: arte
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  convert: ^3.1.1
  http: ^1.1.2
  logging_colorful: ^1.1.1
  supabase: ^2.0.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
